### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Godvil** [MiraWaNeko/DiscordIntegration#172]
### Base informations
**Minecraft version:** 1.12.2

**DiscordIntegration version:** DiscordIntegration-mc1.12.2-3.0.5

**Server type and version:** forge-1.12.2-14.23.5.2768

**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
```
"commands": [{
"name": "whitelist",
"cmd": "/whitelist %args%",
"enabled": true,
"roles": ["role:CENSORED"]
}]
```
Discord channel:
!whitelist reload
Should execute server command.

### Actual behavior
```
[08:57:02] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at chikachi.discord.core.config.discord.CommandConfig.buildCommand(CommandConfig.java:63) ~[CommandConfig.class:?]
        at chikachi.discord.listener.DiscordListener.lambda$tryExecuteCommand$5(DiscordListener.java:217) ~[DiscordListener.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
```

**Comment by Godvil** [comment]
Role permission is represented as role ID, not the role name. Using role name acts the same way.

**Comment by CmmmmmmLau** [comment]
I have the same problem. It look like was conflict with the VanillaFix.

```
[16:10:58] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at chikachi.discord.core.config.discord.CommandConfig.buildCommand(CommandConfig.java:67) ~[CommandConfig.class:?]
	at chikachi.discord.listener.DiscordListener.lambda$tryExecuteCommand$5(DiscordListener.java:217) ~[DiscordListener.class:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
```
