### ISSUE TITLE
Tps will not work in discord no matter what i do

### ISSUE THREAD

**Issue by BatteryVoltic** [MiraWaNeko/DiscordIntegration#38]
Hello,
     I have been getting an issue where the mod will not relay the tps information that i need in 1.7.10. 
i want the command tps to me available to everyone on the server and currently no one can use (including me)
```
"tps": {
                "enabled": true,
                "roles": [],
                "aliases": [],
                "colored": true
```
that is waht my tps configs are. so what am i doing wrong

version: `DiscordIntegration-mc1.7.10-2.1.0.jar`

**Comment by jasgrider** [comment]
Do you have a lot of dimensions on your server? Discord has a 2000 character limit per message which the TPS report will hit if you have more than about 23 dimensions. My Project Ozone 2 server hits that when trying to do !tps

EDIT: 
You should see the exception in the logs on your server when you query tps from discord:
```
[23:13:16] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [23:13:16] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[23:13:16] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [23:13:16] [Fatal] [JDA]: Encountered an exception:
[23:13:16] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [23:13:16] [Fatal] [JDA]: java.lang.UnsupportedOperationException: Cannot build a Message with more than 2000 characters. Please limit your 
input.
        at chikachi.discord.repack.net.dv8tion.jda.MessageBuilder.build(MessageBuilder.java:367)
        at chikachi.discord.repack.net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessageAsync(TextChannelImpl.java:204)
        at chikachi.discord.DiscordClient.sendMessage(DiscordClient.java:136)
        at chikachi.discord.command.discord.TpsCommandConfig.execute(TpsCommandConfig.java:194)
        at chikachi.discord.listener.DiscordListener.onMessageReceived(DiscordListener.java:94)
        at chikachi.discord.repack.net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at chikachi.discord.repack.net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at chikachi.discord.repack.net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at chikachi.discord.repack.net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at chikachi.discord.repack.net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at chikachi.discord.repack.net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at chikachi.discord.repack.net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)
```

**Comment by MiraWaNeko** [comment]
I'm so sorry that I haven't responded to this before now, life happened :/

@battery3996 Could you please respond to what @jasgrider said?
The character limit is ofcause something I'm gonna try find a solution for in upcoming versions.

**Comment by BatteryVoltic** [comment]
It has approx 29 dimensions in PO2......im not sure how many are loaded at once tho....

**Comment by CDAGaming** [comment]
@Chikachi I'm having the same issue here (32 Dimensions in my pack) except there is no error whatsoever, it just does not appear back into discord

**Comment by 132ikl** [comment]
Are you running sponge?

**Comment by 132ikl** [comment]
(Sorry for 2 messages) Also, is it just TPS or do other commands not work
as well?

**Comment by CDAGaming** [comment]
@132ikl It is running SpongeForge, and other commands like !online do work just fine.

**Comment by CDAGaming** [comment]
Turns out out some commands also wont run due to insufficient perms, even though DiscordFakePlayer has been opped
