### ISSUE TITLE
Server crash on server shutdown

### ISSUE THREAD

**Issue by sharkck** [MiraWaNeko/DiscordIntegration#68]
Just noticed this server crash when issuing a stop/shutdown command to the server:

```
[00:46:38] [Server Shutdown Thread/INFO]: Stopping server
[00:46:38] [Server Shutdown Thread/INFO]: Saving players
[00:46:38] [Server Shutdown Thread/INFO] [powerinventory]: Player File: _908f7355-74a7-45b9-827c-a41d920511c4.opi
[00:46:38] [Server Shutdown Thread/INFO] [powerinventory]: Player File: _908f7355-74a7-45b9-827c-a41d920511c4.opibk
[00:46:38] [Server Shutdown Thread/INFO]: sharkck lost connection: Server closed
[00:46:38] [Server Shutdown Thread/INFO]: sharkck left the game
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@2d341d97:
java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:229) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:826) ~[MinecraftServer.class:?]
        at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38) ~[MorpheusEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1363_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) [FMLCommonHandler.class:?]
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) [pj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:839) [oy.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:452) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:281) [oy$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1377) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1389) [MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:277) [oy.class:?]
        at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1070) [pj.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:430) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1563) [MinecraftServer$4.class:?]
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: Index: 16 Listeners:
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 0: HIGH
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 1: ASM: blusunrize.immersiveengineering.common.EventHandler@5f2676d5 onLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 2: NORMAL
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 3: ASM: class codechicken.chunkloader.manager.OrganiserStorage onPlayerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 4: ASM: net.geforcemods.securitycraft.handlers.ForgeEventHandler@1abccc77 onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 5: ASM: crafttweaker.mc1120.events.CommonEventHandler@53ff1248 onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 6: ASM: cavern.handler.CavebornEventHooks@38304e5e onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 7: ASM: chanceCubes.listeners.PlayerConnectListener@39ea9b5 onPlayerLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 8: ASM: ic2.core.IC2@2d3a2f54 onPlayerLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 9: ASM: codechicken.enderstorage.network.TankSynchroniser@10f4a7a0 onPlayerLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 10: ASM: class com.feed_the_beast.ftbl.FTBLibEventHandler onPlayerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 11: ASM: thut.api.terrain.TerrainManager@44f887a6 PlayerLoggout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 12: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerNetwork@444e5848 onLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 13: ASM: codechicken.chunkloader.handler.ChunkLoaderEventHandler@2b4a113d playerLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 14: ASM: com.jaquadro.minecraft.storagedrawers.StorageDrawers@1feea15f onPlayerDisconnect(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 15: ASM: tamaized.voidcraft.common.events.XiaFlightHandler@6b95e78a playerLoggedOut(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 16: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@796319c0 loggedOutEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 17: ASM: org.dynmap.forge.DynmapPlugin$PlayerTracker@493291db onPlayerLogout(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 18: LOWEST
[00:46:38] [Server Shutdown Thread/ERROR] [FML]: 19: ASM: chikachi.discord.listener.MinecraftListener@563f4ac5 onPlayerLeave(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1329)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1314)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:277)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1070)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:430)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1563)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:229)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:826)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1363_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:839)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:452)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:281)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1377)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1389)
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    ... 4 more
> Exception in thread "Server Shutdown Thread" Press any key to continue . . .
```

**Comment by MiraWaNeko** [comment]
I don't see any indication that this has anything to do with DiscordIntegration.
Only mention of DiscordIntegration is that it's having a listener for player leaves.

The only mod I see that is part of the stack trace is Morpheus.
```
[00:46:38] [Server Shutdown Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:    at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38)
```
