### ISSUE TITLE
NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

### ISSUE THREAD

**Issue by codewarrior0** [MiraWaNeko/DiscordIntegration#78]
### Base informations
**Minecraft version:**
1.7.10

**DiscordIntegration version:**
3.0.1

### Traceback

```
java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at chikachi.discord.DiscordIntegration$2.replace(DiscordIntegration.java:119)
	at chikachi.discord.core.Patterns.executeReplacement(Patterns.java:81)
	at chikachi.discord.core.Patterns.minecraftToDiscord(Patterns.java:62)
	at chikachi.discord.core.Message.formatText(Message.java:201)
	at chikachi.discord.core.Message.formatText(Message.java:122)
	at chikachi.discord.core.Message.toWebhook(Message.java:77)
	at chikachi.discord.core.DiscordClient.broadcast(DiscordClient.java:211)
```

Traceback suggests this is related to color codes. `ChatFormatting` is a client-side class and not available on servers. [This issue](https://github.com/simeonradivoev/MatterOverdrive/issues/504) suggests replacing it [with `net.minecraft.util.text.TextFormatting`](https://github.com/simeonradivoev/MatterOverdrive/commit/89bc56fc3316e62b553da7ac63ff6a6ce6b2846e).

**Comment by redsgreens** [comment]
I am having a similar issue on 1.8.9. 

java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
        at chikachi.discord.DiscordIntegration$1.post(DiscordIntegration.java:99)
        at chikachi.discord.core.Patterns.executeReplacement(Patterns.java:85)
        at chikachi.discord.core.Patterns.discordToMinecraft(Patterns.java:50)
        at chikachi.discord.core.Message.formatText(Message.java:205)
        at chikachi.discord.core.Message.getFormattedTextMinecraft(Message.java:226)
        at chikachi.discord.listener.DiscordListener.onMessageReceived(DiscordListener.java:135)
        at chikachi.discord.repack.net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:385)
        at chikachi.discord.repack.net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at chikachi.discord.repack.net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
        at chikachi.discord.repack.net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
        at chikachi.discord.repack.net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at chikachi.discord.repack.net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:768)
        at chikachi.discord.repack.net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:498)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at chikachi.discord.repack.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by C0LiSii0N** [comment]
Apparently I found that it's supposed to be 
net.minecraft.util.text.TextFormatting;
 instead of 
com.mojang.realmsclient.gui.ChatFormatting;
