### ISSUE TITLE
NoClassDefFoundError: org/apache/http/nio/reactor/IOReactorException

### ISSUE THREAD

**Issue by MiraWaNeko** [MiraWaNeko/DiscordIntegration#8]
Created from tweet by XGISKIPPY : https://twitter.com/XGISKIPPY/status/742594496576131074

```
java.lang.NoClassDefFoundError: org/apache/http/nio/reactor/IOReactorException
    at chikachi.discord.repack.com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151) ~[HttpClientHelper.class:?]
    at chikachi.discord.repack.com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131) ~[HttpClientHelper.class:?]
    at chikachi.discord.repack.com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56) ~[BaseRequest.class:?]
    at chikachi.discord.repack.net.dv8tion.jda.requests.Requester.exec(Requester.java:92) ~[Requester.class:?]
    at chikachi.discord.repack.net.dv8tion.jda.requests.Requester.get(Requester.java:47) ~[Requester.class:?]
    at chikachi.discord.repack.net.dv8tion.jda.entities.impl.JDAImpl.validate(JDAImpl.java:128) ~[JDAImpl.class:?]
    at chikachi.discord.repack.net.dv8tion.jda.entities.impl.JDAImpl.login(JDAImpl.java:114) ~[JDAImpl.class:?]
    at chikachi.discord.repack.net.dv8tion.jda.JDABuilder.buildAsync(JDABuilder.java:248) ~[JDABuilder.class:?]
    at chikachi.discord.DiscordClient.connect(DiscordClient.java:70) ~[DiscordClient.class:?]
    at chikachi.discord.Proxy.onServerAboutToStart(Proxy.java:38) ~[Proxy.class:?]
    at chikachi.discord.ChikachiDiscord.onServerAboutToStart(ChikachiDiscord.java:56) ~[ChikachiDiscord.class:?]
```

Full stacktrace: http://pastebin.com/raw/GYznCYDG

**Comment by SkippTekk** [comment]
Meep

**Comment by TATDK** [comment]
Okay, just got home for work.

So basically the mod isn't supposed to be running on the client, on 1.8.9 and up I can set it so Forge ignores the mod on clientside, but that option isn't there on 1.7.10.

**Comment by TATDK** [comment]
Just tried adding something, could you try see if this fixes the issue?

[ChikachiDiscord-mc1.7.10-1.3.1.zip](https://github.com/Chikachi/ChikachiDiscord/files/314222/ChikachiDiscord-mc1.7.10-1.3.1.zip)

Remember to unzip it so you have the .jar file ;)

**Comment by SkippTekk** [comment]
downloading now. and testing.

Oh! i didn't know i had to unzip it! _he says sarcastically_

**Comment by MiraWaNeko** [comment]
Just wanted to be sure ^w^

**Comment by SkippTekk** [comment]
It works! 
![2016-06-14_11 50 04](https://cloud.githubusercontent.com/assets/6195158/16053521/6f6a73ea-3226-11e6-86ee-41ca5576ad2a.png)
