### ISSUE TITLE
Bots Not Showing. [Confirmed Discord Categories Issue] [Temp Fix Detailed] 

### ISSUE THREAD

**Issue by Inrixia** [MiraWaNeko/DiscordIntegration#91]
### Base informations
**Minecraft version:**
1.7.10

**DiscordIntegration version:**
3.0.2
2.1.0
1.4.0

**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/2Q0HFSRF <- 3.0.2 Config
https://pastebin.com/2idBbHPL <- 2.1.0 Config
https://pastebin.com/SVfnAQ2u <- 1.4.0 Config

### Expected behavior
Bots relay chat normally between servers.

### Actual behavior
At best I can receive messages from minecraft but not send messages from discord and commands in discord don't work. All our 1.10 bots seem to be working fine but no matter what bot version I try to use for our 1.7.10 servers it will not work.

### Steps to reproduce
Just run those configs. I think it might be a issue with the new channel organisation that discord has done.

**EDIT: Electro (One of our admins) Has figured out that the issue is to do with the new discord channel organisers and to fix the bots you have to remove all organisers as per his post below.**

**Only main issue now is a fix so the bots will work with the organisers.**

**Comment by Inrixia** [comment]
Just tested with version 2.1.0, same issue. It seems to be working fine for minecraft version 1.10 and up but all our 1.7.10 servers wont work. The 2.1.0 test was using the same config "just converted to the new version see the above configs" for one of our 1.10 servers which is working fine, so I'm lost as to whats causing it to break. I also tested using our 1.10 bots and it wont work with those either, so the issue appears to be 1.7.10 only, but I'm going to double check that.

Though on 2.1.0 and the older version we are at least receiving messages from minecraft. The latest version just dosnt work at all.

**Comment by wolfhound871** [comment]
having same issue is there a fix yet or is this discord also i even tryed moving the channel back out of the new organizer and still no dice this might be an issue with discord to get it fixed maybe not mod related just throwing that out there to think about

**Comment by Inrixia** [comment]
No fix yet. Pretty sure it has something to do with discord. Hopefully @Chikachi or @TATDK will be able to look into it and fix it. :)

**Comment by Inrixia** [comment]
Also I should note, that the channel we have our bots linked to is not in a category.
EDIT: Oops, didn't mean to close that... Its 4AM I need to sleep :P

**Comment by Electrofried** [comment]
To add to this, specificly the error is:


[06:39:26] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [06:39:26] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Voice Channels","position":2,"id":"360712685375193088","type":4}
[06:39:26] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [06:39:26] [Fatal] [JDASocket]: Encountered an exception:
[06:39:26] [ReadingThread/INFO] [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.utils.SimpleLog:print:396]: [06:39:26] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 360712685375193088
        at chikachi.discord.repack.net.dv8tion.jda.handle.EntityBuilder.createGuildChannelPass(EntityBuilder.java:353)
        at chikachi.discord.repack.net.dv8tion.jda.handle.EntityBuilder.createGuildSecondPass(EntityBuilder.java:275)
        at chikachi.discord.repack.net.dv8tion.jda.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:59)
        at chikachi.discord.repack.net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at chikachi.discord.repack.net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:587)
        at chikachi.discord.repack.net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at chikachi.discord.repack.com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)


I believe this issues started when the new categories system was rolled out. Even though the channel it is trying to read is not in a category it is not recognising it as a text channel.

**Comment by Velikss** [comment]
I have exactly the same problem on my 1.7.10 server with version 2.1.0. Really hope this gets fixed since it's a great feature!
My console says the same as @Electrofried posted above. Weirdly it is sending messages from MC to discord but not the otherway around..

**Comment by Electrofried** [comment]
Issue is with the new categories system on discord, removing all categories resolves the issue. You also have to remove any automatically created "voice" category or the bot gets redirected to join those.

**Comment by wolfhound871** [comment]
contacted discord support they were no help read below at what they said ..
{Sorry about that! Unfortunately, the answer you're looking for is a bit beyond what we offer for our general support channel. Instead, you may want to try troubleshooting the issue in the Discord API server if there's an error/problem in the docs. If you're not already there, here's an invite to the server:

https://discord.gg/discord-api}

**Comment by MiraWaNeko** [comment]
Could you try and see if the 3.0.3 version of DiscordIntegration fixes the issue?

**Comment by Electrofried** [comment]
version 3.0.3 crashes on load with this https://pastebin.com/5gM3jvbH so can not test sorry :(

**Comment by MiraWaNeko** [comment]
That's strange, my build server should have caught that.

**Comment by Tencao** [comment]
@Chikachi 3.0.3 works for 1.12.2, tested on my server and messages and the bot appear correctly.

**Comment by wolfhound871** [comment]
dont closed mean its fixed https://puu.sh/xSHnv/6b000ad40b.png what did i do wrong then cause they cant see anyone type from discord do you want me to push a config link ? and players say they cant see the other server talking in game nothing has changed from 2.1.0 worked just as good both servers cant see messages and discord cant type into game still

**Comment by Inrixia** [comment]
@wolfhound871 Its working fine for me, I'm using the configs stated here. Double check your configs and that your bots have the right permissions.

**Comment by Konigtiger87** [comment]
My bot just stopped working on a server restart,and it may be due to this categories issue.  Can someone take a look at my pastebin?  Bot comes online and no errors in the server cmd.

https://pastebin.com/7pyn8sMk
